spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:tcp://localhost/~/userDB 
    driver-class-name: org.h2.Driver
    username: sa
    password:

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect #hibernate가 사용하는 데이터베이스 플랫폼
    hibernate:
      ddl-auto: create #hibernate가 데이터베이스 스키마를 자동으로 생성하거나 업데이트
    show-sql: true #hibernate가 실행되는 SQL문을 콘솔에 출력

  h2:
    console:
      enabled: true #h2 콘솔 활성화(url로 접근 가능)
      path: /h2-console #h2 콘솔 경로(http://localhost:포트번호/h2-console)
      settings:
        web-allow-others: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan:
    - HS_hrs.user_service.Controller

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.web: DEBUG
# server:
#   port: 0
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: dSYZ9U9tOUqj5ThwY3hzxjYpWTpTrmjn3HgoU3duW04=