spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:testdb #인메모리 h2데이터베이스 사용(mem: 인메모리)
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect #hibernate가 사용하는 데이터베이스 플랫폼
    hibernate:
      ddl-auto: update #hibernate가 데이터베이스 스키마를 자동으로 생성하거나 업데이트
    show-sql: true #hibernate가 실행되는 SQL문을 콘솔에 출력

  h2:
    console:
      enabled: true #h2 콘솔 활성화(url로 접근 가능)
      path: /h2-console #h2 콘솔 경로(http://localhost:포트번호/h2-console)
      settings:
        web-allow-others: true
# server:
#   port: 0
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
