spring:
  application:
    name: employee-service
    
  datasource:
    url: jdbc:h2:tcp://localhost/~/employeeDB
    driver-class-name: org.h2.Driver
    username: sa
    password:

  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      group-id: employee-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

springdoc: 
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan:
    - HS_hrs.employee_service.Controller

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.web: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka